# Heart Attack Prediction Model 
This model is based on quantitative and qualitative data of the diffrent patients, from common measured health parameters like Blood Preasure, Cholerterol levels, Heart rate etc, to lifestyle choices such as Excercise rate, Alcohol consumption and so on.

In [1]:
import numpy as nu
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [2]:
import os

folder = os.getcwd()

In [3]:
print(folder)

c:\Users\USER\Desktop\Codes\Git_\AI\Predictive_Heart_Attack_Model

In [4]:
Heart_Data =pd.read_csv ( f"{folder}/heart_attack_russia.csv" )
print(Heart_Data.info())
print(Heart_Data.head())
print(Heart_Data.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     50000 non-null  int64
 1   Age                    50000 non-null  int64
 2   Gender                 50000 non-null  object
 3   Region                 50000 non-null  object
 4   Blood_Pressure         50000 non-null  float64
 5   Cholesterol            50000 non-null  float64
 6   BMI                    50000 non-null  float64
 7   Heart_Rate             50000 non-null  int64
 8   Exercise_Level         50000 non-null  object
 9   Smoking                50000 non-null  bool
 10  Alcohol_Consumption    24976 non-null  object
 11  Diabetes               50000 non-null  bool
 12  Family_History         50000 non-null  bool
 13  Stress_Level           50000 non-null  int64
 14  Heart_Attack           50000 non-null  bool
 15  Angina                 50000 non-null  bool
 16  Heart_Disease_History  50000 non-null  bool
 17  Diet                   50000 non-null  object
 18  Sleep_Hours            50000 non-null  float64
 19  Occupation             50000 non-null  object
 20  Income_Level           50000 non-null  object
 21  Physical_Activity      50000 non-null  object
 22  Education_Level        50000 non-null  object
 23  Marital_Status         50000 non-null  object
 24  Urban_Rural            50000 non-null  object
 25  Medication             50000 non-null  bool
 26  Health_Awareness       50000 non-null  int64
 27  Daily_Water_Intake     50000 non-null  float64
 28  Mental_Health          50000 non-null  int64
 29  Obesity                50000 non-null  bool
dtypes: bool(8), float64(5), int64(6), object(11)
memory usage: 8.8+ MB
None
   ID  Age  Gender Region  Blood_Pressure  Cholesterol   BMI  Heart_Rate  \
0   1   50    Male  Rural           110.0        196.5  15.9          76
1   2   40  Female  Urban           138.8        157.5  27.1          82
2   3   26    Male  Rural           116.0        210.1  27.2          71
3   4   54  Female  Rural           133.5        170.5  26.0          74
4   5   19  Female  Urban           108.0        224.5  27.5          67

  Exercise_Level  Smoking  ... Income_Level  Physical_Activity  \
0           High    False  ...          Low                Low
1       Moderate    False  ...          Low           Moderate
2       Moderate    False  ...       Middle               High
3       Moderate     True  ...       Middle           Moderate
4            Low    False  ...       Middle                Low

   Education_Level  Marital_Status  Urban_Rural  Medication  Health_Awareness  \
0          Primary         Married        Rural       False                 5
1           Higher         Married        Urban       False                 1
2          Primary         Married        Urban       False                 4
3           Higher         Married        Urban       False                 2
4           Higher         Widowed        Urban       False                 4

  Daily_Water_Intake  Mental_Health Obesity
0                2.3              5   False
1                5.0              4   False
2                2.4              8   False
3                2.7              6    True
4                3.5              4    True

[5 rows x 30 columns]
(50000, 30)

In [5]:
# Clean Data by filling in missing values with 0
Heart_Data = Heart_Data.fillna("None")

print(Heart_Data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     50000 non-null  int64
 1   Age                    50000 non-null  int64
 2   Gender                 50000 non-null  object
 3   Region                 50000 non-null  object
 4   Blood_Pressure         50000 non-null  float64
 5   Cholesterol            50000 non-null  float64
 6   BMI                    50000 non-null  float64
 7   Heart_Rate             50000 non-null  int64
 8   Exercise_Level         50000 non-null  object
 9   Smoking                50000 non-null  bool
 10  Alcohol_Consumption    50000 non-null  object
 11  Diabetes               50000 non-null  bool
 12  Family_History         50000 non-null  bool
 13  Stress_Level           50000 non-null  int64
 14  Heart_Attack           50000 non-null  bool
 15  Angina                 50000 non-null  bool
 16  Heart_Disease_History  50000 non-null  bool
 17  Diet                   50000 non-null  object
 18  Sleep_Hours            50000 non-null  float64
 19  Occupation             50000 non-null  object
 20  Income_Level           50000 non-null  object
 21  Physical_Activity      50000 non-null  object
 22  Education_Level        50000 non-null  object
 23  Marital_Status         50000 non-null  object
 24  Urban_Rural            50000 non-null  object
 25  Medication             50000 non-null  bool
 26  Health_Awareness       50000 non-null  int64
 27  Daily_Water_Intake     50000 non-null  float64
 28  Mental_Health          50000 non-null  int64
 29  Obesity                50000 non-null  bool
dtypes: bool(8), float64(5), int64(6), object(11)
memory usage: 8.8+ MB
None

## Exploratort Data Analysis

In [6]:
Heart_Data.head()

,ID,Age,Gender,Region,Blood_Pressure,Cholesterol,BMI,Heart_Rate,Exercise_Level,Smoking,...,Income_Level,Physical_Activity,Education_Level,Marital_Status,Urban_Rural,Medication,Health_Awareness,Daily_Water_Intake,Mental_Health,Obesity
0,1,50,Male,Rural,110.0,196.5,15.9,76,High,False,...,Low,Low,Primary,Married,Rural,False,5,2.3,5,False
1,2,40,Female,Urban,138.8,157.5,27.1,82,Moderate,False,...,Low,Moderate,Higher,Married,Urban,False,1,5.0,4,False
2,3,26,Male,Rural,116.0,210.1,27.2,71,Moderate,False,...,Middle,High,Primary,Married,Urban,False,4,2.4,8,False
3,4,54,Female,Rural,133.5,170.5,26.0,74,Moderate,True,...,Middle,Moderate,Higher,Married,Urban,False,2,2.7,6,True
4,5,19,Female,Urban,108.0,224.5,27.5,67,Low,False,...,Middle,Low,Higher,Widowed,Urban,False,4,3.5,4,True

In [7]:
Heart_Data.describe()

,ID,Age,Blood_Pressure,Cholesterol,BMI,Heart_Rate,Stress_Level,Sleep_Hours,Health_Awareness,Daily_Water_Intake,Mental_Health
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000
mean,25000.500000,35.991820,120.058636,199.852762,24.983912,79.988980,5.503700,7.011464,3.007100,2.997782,5.48674
std,14433.901067,14.110139,14.975835,49.998331,5.003784,11.804567,2.870741,1.740651,1.410351,1.149608,2.86076
min,1.000000,12.000000,60.000000,-18.700000,2.900000,60.000000,1.000000,4.000000,1.000000,1.000000,1.00000
25%,12500.750000,24.000000,109.900000,166.100000,21.600000,70.000000,3.000000,5.500000,2.000000,2.000000,3.00000
50%,25000.500000,36.000000,120.050000,199.900000,25.000000,80.000000,6.000000,7.000000,3.000000,3.000000,5.00000
75%,37500.250000,48.000000,130.200000,233.500000,28.400000,90.000000,8.000000,8.500000,4.000000,4.000000,8.00000
max,50000.000000,60.000000,188.400000,398.800000,46.100000,100.000000,10.000000,10.000000,5.000000,5.000000,10.00000

In [ ]:
print("Integer and Float Columns:", Heart_Data.select_dtypes(include=['int64', 'float64']).columns)
print("Boolean Columns:", Heart_Data.select_dtypes(include=['bool']).columns)
print("String Columns:", Heart_Data.select_dtypes(include=['object']).columns)

In [ ]:
integer_columns = Heart_Data[['ID', 'Age', 'Blood_Pressure', 'Cholesterol', 'BMI', 'Heart_Rate',
       'Stress_Level', 'Sleep_Hours', 'Health_Awareness', 'Daily_Water_Intake',
       'Mental_Health']]

integer_columns = pd.DataFrame(integer_columns)
integer_columns.head()

In [ ]:
boolean_columns = Heart_Data[['Smoking', 'Diabetes', 'Family_History', 'Heart_Attack', 'Angina',
       'Heart_Disease_History', 'Medication', 'Obesity']]

boolean_columns.head()
boolean_columns = pd.DataFrame(boolean_columns)
boolean_columns.info()

In [ ]:
string_columns = Heart_Data[['Gender', 'Region', 'Exercise_Level', 'Alcohol_Consumption', 'Diet',
       'Occupation', 'Income_Level', 'Physical_Activity', 'Education_Level',
       'Marital_Status', 'Urban_Rural']]

string_columns = pd.DataFrame(string_columns)
string_columns.head()

In [ ]:
for column in string_columns:
    Encode = LabelEncoder()
    Heart_Data[column] = Encode.fit_transform(Heart_Data[column])
    print(f"{column} unique values after encoding:", Heart_Data[column].unique())

In [ ]:
Heart_Data.info()

In [ ]:
for column in boolean_columns:
        Heart_Data[column] = Heart_Data[column].astype(int)
        print(f"{column} values after conversion:", Heart_Data[column].unique())

In [ ]:
Heart_Data.info()

In [ ]:
Heart_Data['Heart_Attack'].value_counts()

Data Skewed toward 0 value
balance it out

In [ ]:
X = Heart_Data.drop(['Heart_Attack'], axis=1)

Y = Heart_Data["Heart_Attack"]

In [ ]:
X.shape

In [ ]:
Y.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
# Scale Data
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.fit_transform(X_test)
y_train = Scaler.fit_transform(y_train)
y_test = Scaler.fit_transform(y_test)

In [ ]:
y_train.shape

In [ ]:
kn = KNeighborsRegressor()
kn.fit(X_train,y_train)
pre_1=kn.predict(X_test)
print( f"Accuracy Score = {accuracy_score(y_test, pre_1.round())}")
print("Classification Report:")
print(classification_report(y_test, pre_1.round()))
stat_1 = classification_report(y_test, pre_1.round(), output_dict= True)

In [ ]:
stat_1 = pd.DataFrame(stat_1).transpose()

In [ ]:
metrics_to_plot = ['precision', 'recall', 'f1-score']
df_plot = stat_1.loc[stat_1.index.difference(['accuracy', 'macro avg', 'weighted avg']), metrics_to_plot]

df_plot.plot(kind='bar', figsize=(10, 6))
plt.title('Classification Report Metrics per Class')
plt.ylabel('Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Metric')
plt.tight_layout()
plt.show()

In [ ]:
lr=LinearRegression()
lr.fit(X_train,y_train)
pre_2 = lr.predict(X_test)
print( f"Accuracy Score = {accuracy_score(y_test, pre_2.round())}")
print("Classification Report:")
print(classification_report(y_test, pre_2.round()))
stat_2 = classification_report(y_test, pre_2.round(), output_dict= True)

In [ ]:
stat_2 = pd.DataFrame(stat_2).transpose()

In [ ]:
metrics_to_plot = ['precision', 'recall', 'f1-score']
df_plot = stat_2.loc[stat_2.index.difference(['accuracy', 'macro avg', 'weighted avg']), metrics_to_plot]

df_plot.plot(kind='bar', figsize=(10, 6))
plt.title('Classification Report Metrics per Class')
plt.ylabel('Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Metric')
plt.tight_layout()
plt.show()