# Lung Cancer Regression Model

In [2]:
import os
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.neighbors import KNeighborsRegressor

In [3]:
path = os.getcwd()

In [4]:
Lung_Data = pd.read_csv(f"{path}/Lung_Cancer_Trends_Realistic.csv")

In [5]:
Lung_Data.head()

,Patient_ID,Age,Gender,Smoking_Status,Years_Smoking,Cigarettes_Per_Day,Secondhand_Smoke_Exposure,Occupation_Exposure,Air_Pollution_Level,Family_History,...,Diet_Quality,Region,Income_Level,Education_Level,Access_to_Healthcare,Screening_Frequency,Chronic_Lung_Disease,Lung_Cancer_Stage,Diagnosis_Year,Survival_Status
0,P100000,76,Female,Never,6,37,Low,Diesel Fumes,Low,Yes,...,Poor,West,Middle,Tertiary,Good,Regularly,No,Stage II,2008,Alive
1,P100001,39,Male,Never,30,39,Low,Silica,Low,Yes,...,Average,North,Middle,Primary,Poor,Occasionally,Yes,NaN,2002,Alive
2,P100002,85,Male,Former,47,14,High,Asbestos,Low,Yes,...,Good,South,High,Tertiary,Average,Regularly,No,Stage II,2007,Deceased
3,P100003,45,Female,Current,45,32,Medium,Silica,High,No,...,Good,West,Low,Secondary,Average,Never,Yes,NaN,2011,Alive
4,P100004,48,Female,Never,46,26,Medium,Silica,Low,No,...,Good,North,Low,Tertiary,Average,Regularly,No,NaN,2016,Alive

In [6]:
Lung_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 3000 non-null   object
 1   Age                        3000 non-null   int64
 2   Gender                     3000 non-null   object
 3   Smoking_Status             3000 non-null   object
 4   Years_Smoking              3000 non-null   int64
 5   Cigarettes_Per_Day         3000 non-null   int64
 6   Secondhand_Smoke_Exposure  3000 non-null   object
 7   Occupation_Exposure        2256 non-null   object
 8   Air_Pollution_Level        3000 non-null   object
 9   Family_History             3000 non-null   object
 10  Genetic_Markers_Positive   3000 non-null   object
 11  BMI                        3000 non-null   float64
 12  Physical_Activity_Level    3000 non-null   object
 13  Alcohol_Consumption        2025 non-null   object
 14  Diet_Quality               3000 non-null   object
 15  Region                     3000 non-null   object
 16  Income_Level               3000 non-null   object
 17  Education_Level            3000 non-null   object
 18  Access_to_Healthcare       3000 non-null   object
 19  Screening_Frequency        3000 non-null   object
 20  Chronic_Lung_Disease       3000 non-null   object
 21  Lung_Cancer_Stage          598 non-null    object
 22  Diagnosis_Year             3000 non-null   int64
 23  Survival_Status            3000 non-null   object
dtypes: float64(1), int64(4), object(19)
memory usage: 562.6+ KB

In [7]:
Lung_Data['Occupation_Exposure'].unique()
Lung_Data['Occupation_Exposure'] = Lung_Data['Occupation_Exposure'].fillna('Unkown')
Lung_Data['Occupation_Exposure'].unique()

array(['Diesel Fumes', 'Silica', 'Asbestos', 'Unkown'], dtype=object)

In [8]:
Lung_Data['Alcohol_Consumption'].unique()
Lung_Data['Alcohol_Consumption'] = Lung_Data['Alcohol_Consumption'].fillna('Unknown')
Lung_Data['Alcohol_Consumption'].unique()

array(['Moderate', 'High', 'Unknown'], dtype=object)

In [9]:
Lung_Data['Lung_Cancer_Stage'].unique()
Lung_Data['Lung_Cancer_Stage'] = Lung_Data['Lung_Cancer_Stage'].fillna('Unkown')
Lung_Data['Lung_Cancer_Stage'].unique()

array(['Stage II', 'Unkown', 'Stage III', 'Stage IV', 'Stage I'],
      dtype=object)

In [10]:
Lung_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Patient_ID                 3000 non-null   object
 1   Age                        3000 non-null   int64
 2   Gender                     3000 non-null   object
 3   Smoking_Status             3000 non-null   object
 4   Years_Smoking              3000 non-null   int64
 5   Cigarettes_Per_Day         3000 non-null   int64
 6   Secondhand_Smoke_Exposure  3000 non-null   object
 7   Occupation_Exposure        3000 non-null   object
 8   Air_Pollution_Level        3000 non-null   object
 9   Family_History             3000 non-null   object
 10  Genetic_Markers_Positive   3000 non-null   object
 11  BMI                        3000 non-null   float64
 12  Physical_Activity_Level    3000 non-null   object
 13  Alcohol_Consumption        3000 non-null   object
 14  Diet_Quality               3000 non-null   object
 15  Region                     3000 non-null   object
 16  Income_Level               3000 non-null   object
 17  Education_Level            3000 non-null   object
 18  Access_to_Healthcare       3000 non-null   object
 19  Screening_Frequency        3000 non-null   object
 20  Chronic_Lung_Disease       3000 non-null   object
 21  Lung_Cancer_Stage          3000 non-null   object
 22  Diagnosis_Year             3000 non-null   int64
 23  Survival_Status            3000 non-null   object
dtypes: float64(1), int64(4), object(19)
memory usage: 562.6+ KB

In [11]:
Lung_Data = pd.DataFrame(Lung_Data)

## Exploratory Data Analysis

In [12]:
Lung_Data.describe()

,Age,Years_Smoking,Cigarettes_Per_Day,BMI,Diagnosis_Year
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,56.654333,24.226000,19.624000,24.972633,2012.129667
std,18.740880,14.292924,11.430289,4.962199,7.248105
min,25.000000,0.000000,0.000000,2.600000,2000.000000
25%,41.000000,12.000000,10.000000,21.600000,2006.000000
50%,57.000000,24.000000,19.000000,24.800000,2012.000000
75%,73.000000,36.000000,29.000000,28.300000,2018.000000
max,89.000000,49.000000,39.000000,45.700000,2024.000000

In [13]:
#print('Number columns' ,Lung_Data.select_dtypes(include=['int64','float64']).columns)

In [14]:
print('String columns' ,Lung_Data.select_dtypes(include='object').columns)

String columns Index(['Patient_ID', 'Gender', 'Smoking_Status', 'Secondhand_Smoke_Exposure',
       'Occupation_Exposure', 'Air_Pollution_Level', 'Family_History',
       'Genetic_Markers_Positive', 'Physical_Activity_Level',
       'Alcohol_Consumption', 'Diet_Quality', 'Region', 'Income_Level',
       'Education_Level', 'Access_to_Healthcare', 'Screening_Frequency',
       'Chronic_Lung_Disease', 'Lung_Cancer_Stage', 'Survival_Status'],
      dtype='object')

In [15]:

strings= Lung_Data[['Patient_ID', 'Gender', 'Smoking_Status', 'Secondhand_Smoke_Exposure',
       'Occupation_Exposure', 'Air_Pollution_Level', 'Family_History',
       'Genetic_Markers_Positive', 'Physical_Activity_Level',
       'Alcohol_Consumption', 'Diet_Quality', 'Region', 'Income_Level',
       'Education_Level', 'Access_to_Healthcare', 'Screening_Frequency',
       'Chronic_Lung_Disease', 'Lung_Cancer_Stage', 'Survival_Status']]

strings = pd.DataFrame(strings)

In [16]:

for column in strings:
    Encode = LabelEncoder()
    Lung_Data[column] = Encode.fit_transform(Lung_Data[column])
    print(f"{column} Unique values after conversion= {Lung_Data[column].unique()}")

Patient_ID Unique values after conversion= [   0    1    2 ... 2997 2998 2999]
Gender Unique values after conversion= [0 1]
Smoking_Status Unique values after conversion= [2 1 0]
Secondhand_Smoke_Exposure Unique values after conversion= [1 0 2]
Occupation_Exposure Unique values after conversion= [1 2 0 3]
Air_Pollution_Level Unique values after conversion= [1 0 2]
Family_History Unique values after conversion= [1 0]
Genetic_Markers_Positive Unique values after conversion= [0 1]
Physical_Activity_Level Unique values after conversion= [2 0 1]
Alcohol_Consumption Unique values after conversion= [1 0 2]
Diet_Quality Unique values after conversion= [2 0 1]
Region Unique values after conversion= [3 1 2 0]
Income_Level Unique values after conversion= [2 0 1]
Education_Level Unique values after conversion= [2 0 1]
Access_to_Healthcare Unique values after conversion= [1 2 0]
Screening_Frequency Unique values after conversion= [2 1 0]
Chronic_Lung_Disease Unique values after conversion= [0 1]
Lung_Cancer_Stage Unique values after conversion= [1 4 2 3 0]
Survival_Status Unique values after conversion= [0 1]

In [17]:
#Lung_Data.drop(['Patient_ID','Education_Level','Income_Level','Diagnosis_Year'], axis= 1)

In [18]:
#Lung_Data.info()

In [19]:
#Lung_Data['Lung_Cancer_Stage'].value_counts()

In [20]:
X = Lung_Data.drop(['Lung_Cancer_Stage'], axis=1)
y = Lung_Data['Lung_Cancer_Stage']

In [21]:
y = pd.DataFrame(y)
type(y)

pandas.core.frame.DataFrame

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2 , random_state=50)

In [23]:
print(y_train.shape)

(2400, 1)

In [24]:
"""
scale = StandardScaler()
X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.fit_transform(X_test)
Y_train_scale = scale.fit_transform(y_train)
Y_test_scale = scale.fit_transform(y_test)
"""

'\nscale = StandardScaler()\nX_train_scale = scale.fit_transform(X_train)\nX_test_scale = scale.fit_transform(X_test)\nY_train_scale = scale.fit_transform(y_train)\nY_test_scale = scale.fit_transform(y_test)\n'

In [25]:
ln_1 = LogisticRegression(max_iter = 10000, random_state=0)
ln_1.fit(X_train,y_train)

ln_1_perd = ln_1.predict(X_test)
ln_1_prob = ln_1.predict_proba(X_test)[:, 1]

c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [35]:
print("Accuracy:", accuracy_score(y_test, ln_1_perd))
print("Precision:", precision_score(y_test, ln_1_perd , average='weighted'))
print("Recall:", recall_score(y_test, ln_1_perd, average='weighted'))
print("F1 Score:", f1_score(y_test, ln_1_perd, average='weighted'))
#print("AUC-ROC:", roc_auc_score(y_test, ln_1_perd, multi_class='ovr'))

Accuracy: 0.7916666666666666
Precision: 0.626736111111111
Recall: 0.7916666666666666
F1 Score: 0.6996124031007752

c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
rep = classification_report(y_test,pre.round(), output_dict = True)

rep = pd.DataFrame(rep).transpose();

In [ ]:
rep

In [ ]:
metrics_to_plot = ['precision', 'recall', 'f1-score']
df_plot = rep.loc[rep.index.difference(['accuracy', 'macro avg', 'weighted avg']), metrics_to_plot]

df_plot.plot(kind='bar', figsize=(10, 6))
plt.title('Classification Report Metrics per Class')
plt.ylabel('Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Metric')
plt.tight_layout()
plt.show()